version: '3.7'

services:
  customer-api:
    build:
      context: .
      dockerfile: FastTechFoods.Customer.API/Dockerfile
    container_name: customer-api
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    networks:
      - default
      
  customer-worker:
    build:
      context: .
      dockerfile: FastTechFoods.Customer.Worker/Dockerfile
    container_name: customer-worker
    depends_on:
      - rabbitmq
    networks:
      - default

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter-customer
    networks:
      - default

networks:
  default:
    external:
      name: fiap-hackaton-fasttechfoods_default

volumes:
  grafana-data:
